@extends('layouts.main')

@section('title', 'Berita')

@section('content')
<style>
    .banner-berita {
            background: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200') center/cover no-repeat;
                    height: 250px;
                            display: flex;
                                    align-items: center;
                                        }
                                            .banner-title {
                                                    font-weight: 800;
                                                            letter-spacing: 2px;
                                                                }
                                                                    .card-berita-utama {
                                                                            border-radius: 15px;
                                                                                    overflow: hidden;
                                                                                            box-shadow: 0 8px 24px rgba(0,0,0,0.05);
                                                                                                }
                                                                                                    .card-berita-samping {
                                                                                                            border-radius: 12px;
                                                                                                                    overflow: hidden;
                                                                                                                            box-shadow: 0 4px 12px rgba(0,0,0,0.04);
                                                                                                                                    transition: transform 0.2s;
                                                                                                                                        }
                                                                                                                                            .card-berita-samping:hover {
                                                                                                                                                    transform: translateY(-3px);
                                                                                                                                                        }
                                                                                                                                                        </style>

                                                                                                                                                        <!-- 1. HEADER BANNER BERITA -->
                                                                                                                                                        <div class="banner-berita text-white mb-5">
                                                                                                                                                            <div class="container">
                                                                                                                                                                    <h1 class="text-uppercase banner-title mb-0">Berita Kami</h1>
                                                                                                                                                                        </div>
                                                                                                                                                                        </div>

                                                                                                                                                                        <!-- 2. KONTEN UTAMA BERITA -->
                                                                                                                                                                        <div class="container my-5">
                                                                                                                                                                            <div class="row g-4">
                                                                                                                                                                                    
                                                                                                                                                                                            <!-- KOLOM KIRI: BERITA UTAMA (BESAR) -->
                                                                                                                                                                                                    <div class="col-lg-7">
                                                                                                                                                                                                                <div class="card card-berita-utama border-0 h-100">
                                                                                                                                                                                                                                <img src="https://images.unsplash.com/photo-1498837167922-ddd27525d352?q=80&w=800" class="card-img-top" alt="Berita Utama" style="height: 380px; object-fit: cover;">
                                                                                                                                                                                                                                                <div class="card-body p-4">
                                                                                                                                                                                                                                                                    <h3 class="card-title fw-bold text-uppercase mb-3" style="color: #ffc107;">MENGULIK KULINER TRADISIONAL DI ERA MODERN</h3>
                                                                                                                                                                                                                                                                                        <p class="text-muted small mb-3">📅 2 Juli 2026 | By Admin</p>
                                                                                                                                                                                                                                                                                                            <p class="text-secondary lh-lg mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ornare, augue eu rutrum commodo, dui diam convallis arcu, eget consectetur ex sem eget lacus. Nullam vitae dignissim neque, vel luctus ex. Fusce sit amet viverra ante. Ut enim ad minim veniam, quis nostrud exercitation.</p>
                                                                                                                                                                                                                                                                                                                                <p class="text-muted lh-lg mb-0">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                            <!-- KOLOM KANAN: DAFTAR BERITA LAIN (KECIL-KECIL) -->
                                                                                                                                                                                                                                                                                                                                                                                    <div class="col-lg-5 d-flex flex-column gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                <h4 class="fw-bold text-uppercase mb-2" style="letter-spacing: 1px;">Berita Populer</h4>
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                        <!-- Berita Kecil 1 -->
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="card card-berita-samping border-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="row g-0 align-items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="col-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img src="https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=300" class="img-fluid h-100" alt="Berita 1" style="object-fit: cover; min-height: 120px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="col-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="card-body py-2 px-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h5 class="card-title fw-bold text-uppercase mb-2" style="font-size: 14px; line-height: 1.4;">TIPS MENYAJIKAN MAKANAN AGAR TETAP SEGAR</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p class="card-text text-muted small mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <!-- Berita Kecil 2 -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="card card-berita-samping border-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="row g-0 align-items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="col-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <img src="https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=300" class="img-fluid h-100" alt="Berita 2" style="object-fit: cover; min-height: 120px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="col-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="card-body py-2 px-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h5 class="card-title fw-bold text-uppercase mb-2" style="font-size: 14px; line-height: 1.4;">RAHASIA DI BALIK KELEZATAN BUMBU REMPAH</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p class="card-text text-muted small mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <!-- Berita Kecil 3 -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="card card-berita-samping border-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="row g-0 align-items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="col-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <img src="https://images.unsplash.com/photo-1482049016688-2d3e1b311543?q=80&w=300" class="img-fluid h-100" alt="Berita 3" style="object-fit: cover; min-height: 120px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="col-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="card-body py-2 px-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h5 class="card-title fw-bold text-uppercase mb-2" style="font-size: 14px; line-height: 1.4;">5 REKOMENDASI TEMPAT KULINERAN MINGGU INI</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p class="card-text text-muted small mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @endsection