@extends('layouts.main')

@section('title', 'Home')

@section('content')
<style>
    .hero-title-light { font-weight: 300; letter-spacing: 2px; }
        .hero-title-bold { font-weight: 800; letter-spacing: 1px; }
            .btn-tentang { font-weight: 700; font-size: 12px; letter-spacing: 1px; }
                .floating-card {
                        border: none;
                                border-radius: 15px;
                                        box-shadow: 0 10px 30px rgba(0,0,0,0.05);
                                                margin-top: -80px;
                                                        transition: transform 0.3s;
                                                            }
                                                                .floating-card:hover { transform: translateY(-5px); }
                                                                    .card-img-top-custom {
                                                                            width: 100px;
                                                                                    height: 100px;
                                                                                            object-fit: cover;
                                                                                                    border-radius: 50%;
                                                                                                            margin: -50px auto 0 auto;
                                                                                                                    border: 5px solid #ffffff;
                                                                                                                        }
                                                                                                                        </style>

                                                                                                                        <div class="container my-5 py-3">
                                                                                                                            <div class="row align-items-center">
                                                                                                                                    <div class="col-md-5 mb-5 mb-md-0">
                                                                                                                                                <hr class="border-4 border-dark mb-4" style="width: 80px;">
                                                                                                                                                            <h1 class="text-uppercase text-dark mb-0 hero-title-light">HEALTHY</h1>
                                                                                                                                                                        <h1 class="text-uppercase text-dark mb-4 hero-title-bold" style="font-size: 3.5rem;">TASTY FOOD</h1>
                                                                                                                                                                                    <p class="text-muted mb-4 lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ornare, augue eu rutrum commodo, dui diam convallis arcu, eget consectetur ex sem eget lacus. Nullam vitae dignissim neque, vel luctus ex. Fusce sit amet viverra ante.</p>
                                                                                                                                                                                                <a href="{{ route('tentang') }}" class="btn btn-dark btn-tentang text-uppercase rounded-0 px-4 py-3">Tentang Kami</a>
                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                <div class="col-md-7 text-center position-relative">
                                                                                                                                                                                                                            <img src="https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=600" alt="Tasty Food" class="img-fluid rounded-circle" style="width: 85%; object-fit: cover;">
                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                        <div class="bg-white py-5 text-center my-5">
                                                                                                                                                                                                                                            <div class="container py-4">
                                                                                                                                                                                                                                                    <h2 class="fw-bold text-uppercase mb-3" style="letter-spacing: 1px;">Tentang Kami</h2>
                                                                                                                                                                                                                                                            <p class="text-muted mx-auto lh-lg" style="max-width: 750px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ornare, augue eu rutrum commodo, dui diam convallis arcu, eget consectetur ex sem eget lacus. Nullam vitae dignissim neque, vel luctus ex. Fusce sit amet viverra ante.</p>
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                <div class="position-relative w-100 mb-5" style="height: 350px; background: url('https://images.unsplash.com/photo-1498837167922-ddd27525d352?q=80&w=1200') center/cover no-repeat;">
                                                                                                                                                                                                                                                                    <div class="position-absolute top-0 start-0 w-100 h-100" style="background: rgba(0,0,0,0.2);"></div>
                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                    <div class="container mb-5 pb-5">
                                                                                                                                                                                                                                                                        <div class="row">
                                                                                                                                                                                                                                                                                @for ($i = 1; $i <= 4; $i++)
                                                                                                                                                                                                                                                                                        <div class="col-md-3 mb-5">
                                                                                                                                                                                                                                                                                                    <div class="card floating-card text-center pt-5 pb-4 px-3 bg-white">
                                                                                                                                                                                                                                                                                                                    <img src="https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=150" class="card-img-top-custom shadow-sm" alt="Menu">
                                                                                                                                                                                                                                                                                                                                    <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                        <h5 class="card-title fw-bold text-uppercase mb-3" style="font-size: 16px; letter-spacing: 1px;">LOREM IPSUM</h5>
                                                                                                                                                                                                                                                                                                                                                                            <p class="card-text text-muted small lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ornare, augue eu rutrum commodo.</p>
                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                        @endfor
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                            <!-- 4. SECTION BERITA KAMI -->
                                                                                                                                                                                                                                                                                                                                                                                                                             <div class="container my-5 py-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                 <h3 class="text-center fw-bold text-uppercase mb-5" style="letter-spacing: 1px;">Berita Kami</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                     <div class="row g-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                             <!-- Berita Utama (Kiri - Card Besar) -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div class="col-md-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div class="card border-0 shadow-sm h-100" style="border-radius: 15px; overflow: hidden;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <img src="https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?q=80&w=600" class="card-img-top" alt="Berita Utama" style="height: 300px; object-fit: cover;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div class="card-body p-4 d-flex flex-column justify-content-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <h4 class="card-title fw-bold text-uppercase mb-3" style="font-size: 20px; color: #ffc107;">LOREM IPSUM DOLOR SIT AMET</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <p class="card-text text-muted lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ornare, augue eu rutrum commodo, dui diam convallis arcu, eget consectetur ex sem eget lacus.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <a href="{{ route('berita') }}" class="btn btn-warning text-white fw-bold text-uppercase rounded-0 mt-3 align-self-start px-4 py-2" style="font-size: 12px; background-color: #ffc107; border: none;">Baca Selengkapnya</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <!-- Berita Samping (Kanan - 3 Kolom Kecil) -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div class="col-md-6 d-flex flex-column gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             @for ($i = 1; $i <= 3; $i++)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div class="card border-0 shadow-sm" style="border-radius: 15px; overflow: hidden;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div class="row g-0 align-items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div class="col-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <img src="https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?q=80&w=200" class="img-fluid h-100" alt="Berita Kecil" style="object-fit: cover; min-height: 120px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div class="col-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div class="card-body py-2 px-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <h5 class="card-title fw-bold text-uppercase mb-2" style="font-size: 14px; letter-spacing: 0.5px;">LOREM IPSUM DOLOR SIT AMET</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <p class="card-text text-muted small mb-0 line-clamp-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ornare, augue eu rutrum commodo.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 @endfor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <!-- 5. SECTION GALERI KAMI -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div class="container my-5 py-5 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <h3 class="fw-bold text-uppercase mb-5" style="letter-spacing: 1px;">Galeri Kami</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div class="row g-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <!-- Grid Foto Kue / Makanan -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div class="col-6 col-md-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <img src="https://images.unsplash.com/photo-1511018556340-d16986a1c194?q=80&w=400" class="img-fluid shadow-sm" alt="Galeri" style="border-radius: 12px; height: 200px; width: 100%; object-fit: cover;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div class="col-6 col-md-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <img src="https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=400" class="img-fluid shadow-sm" alt="Galeri" style="border-radius: 12px; height: 200px; width: 100%; object-fit: cover;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div class="col-6 col-md-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <img src="https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=400" class="img-fluid shadow-sm" alt="Galeri" style="border-radius: 12px; height: 200px; width: 100%; object-fit: cover;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div class="col-6 col-md-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <img src="https://images.unsplash.com/photo-1498837167922-ddd27525d352?q=80&w=400" class="img-fluid shadow-sm" alt="Galeri" style="border-radius: 12px; height: 200px; width: 100%; object-fit: cover;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div class="mt-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <a href="{{ route('galeri') }}" class="btn btn-dark text-uppercase rounded-0 px-5 py-3 fw-bold" style="font-size: 12px; letter-spacing: 1px;">Lihat Lebih Banyak</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            @endsection