@extends('layouts.main')

@section('title', 'Kontak')

@section('content')
<style>
    .banner-kontak {
            background: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1200') center/cover no-repeat;
                    height: 250px;
                            display: flex;
                                    align-items: center;
                                        }
                                            .banner-title {
                                                    font-weight: 800;
                                                            letter-spacing: 2px;
                                                                }
                                                                    .form-control:focus {
                                                                            border-color: #ffc107;
                                                                                    box-shadow: 0 0 0 0.25rem rgba(255, 193, 7, 0.25);
                                                                                        }
                                                                                            .info-box {
                                                                                                    background-color: #f8f9fa;
                                                                                                            border-radius: 12px;
                                                                                                                    transition: transform 0.2s;
                                                                                                                        }
                                                                                                                            .info-box:hover {
                                                                                                                                    transform: translateY(-3px);
                                                                                                                                        }
                                                                                                                                        </style>

                                                                                                                                        <!-- 1. HEADER BANNER KONTAK -->
                                                                                                                                        <div class="banner-kontak text-white mb-5">
                                                                                                                                            <div class="container">
                                                                                                                                                    <h1 class="text-uppercase banner-title mb-0">Kontak Kami</h1>
                                                                                                                                                        </div>
                                                                                                                                                        </div>

                                                                                                                                                        <!-- 2. KONTEN UTAMA KONTAK -->
                                                                                                                                                        <div class="container my-5 py-3">
                                                                                                                                                            <div class="row g-5">
                                                                                                                                                                    
                                                                                                                                                                            <!-- KOLOM KIRI: FORM KIRIM PESAN -->
                                                                                                                                                                                    <div class="col-lg-7">
                                                                                                                                                                                                <h3 class="fw-bold text-uppercase mb-4" style="letter-spacing: 1px;">Hubungi Kami</h3>
                                                                                                                                                                                                            <p class="text-muted mb-4">Punya pertanyaan, saran, atau ingin mengadakan acara di Tasty Food? Jangan ragu untuk mengirimkan pesan kepada kami melalui formulir di bawah ini.</p>
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                    <form action="#" method="POST" onsubmit="event.preventDefault(); alert('Pesan berhasil terkirim! (Ini hanya simulasi frontend)');">
                                                                                                                                                                                                                                                    <div class="row g-3">
                                                                                                                                                                                                                                                                        <div class="col-md-6">
                                                                                                                                                                                                                                                                                                <label class="form-label small fw-bold text-uppercase text-secondary">Nama Lengkap</label>
                                                                                                                                                                                                                                                                                                                        <input type="text" class="form-control p-3 bg-light border-0" placeholder="Masukkan nama Anda" required style="border-radius: 8px;">
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                <div class="col-md-6">
                                                                                                                                                                                                                                                                                                                                                                                        <label class="form-label small fw-bold text-uppercase text-secondary">Alamat Email</label>
                                                                                                                                                                                                                                                                                                                                                                                                                <input type="email" class="form-control p-3 bg-light border-0" placeholder="nama@email.com" required style="border-radius: 8px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="col-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label class="form-label small fw-bold text-uppercase text-secondary">Subjek</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="text" class="form-control p-3 bg-light border-0" placeholder="Judul pesan Anda" required style="border-radius: 8px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="col-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label class="form-label small fw-bold text-uppercase text-secondary">Isi Pesan</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <textarea class="form-control p-3 bg-light border-0" rows="5" placeholder="Tuliskan pesan Anda di sini..." required style="border-radius: 8px; resize: none;"></textarea>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="col-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" class="btn btn-warning text-white fw-bold text-uppercase w-100 py-3" style="background-color: #ffc107; border: none; border-radius: 8px; letter-spacing: 1px;">Kirim Pesan</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <!-- KOLOM KANAN: DETAIL INFO & PETA -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="col-lg-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 class="fw-bold text-uppercase mb-4" style="letter-spacing: 1px;">Informasi Resto</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="d-flex flex-column gap-3 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="p-4 info-box border-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h6 class="fw-bold text-uppercase mb-2" style="color: #ffc107;">📍 Lokasi Restoran</h6>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p class="text-muted small mb-0 lh-lg">Jl. Buah Batu No. 123, Malabar, Kec. Lengkong, Kota Bandung, Jawa Barat 40262</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="p-4 info-box border-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h6 class="fw-bold text-uppercase mb-2" style="color: #ffc107;">🕒 Jam Operasional</h6>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p class="text-muted small mb-1">Senin - Jumat: 10.00 - 22.00 WIB</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p class="text-muted small mb-0">Sabtu - Minggu: 09.00 - 23.00 WIB</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <!-- Tiruan Peta Estetik menggunakan Unsplash Gambar Map -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="position-relative overflow-hidden shadow-sm" style="border-radius: 12px; height: 230px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <img src="https://images.unsplash.com/photo-1524661135-423995f22d0b?q=80&w=500" alt="Peta Lokasi" class="w-100 h-100" style="object-fit: cover;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="position-absolute top-50 left-50 translate-middle bg-dark text-white p-2 px-3 small rounded shadow fw-bold text-uppercase" style="opacity: 0.9; font-size: 11px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Lihat di Google Maps
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @endsection