@extends('layouts.main')

@section('title', 'Tentang Kami')

@section('content')
<style>
    .banner-tentang {
            background: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('https://images.unsplash.com/photo-1490815685287-e24a733ec1ba?q=80&w=1200') center/cover no-repeat;
                    height: 250px;
                            display: flex;
                                    align-items: center;
                                        }
                                            .banner-title {
                                                    font-weight: 800;
                                                            letter-spacing: 2px;
                                                                }
                                                                    .img-grid-tentang {
                                                                            border-radius: 15px;
                                                                                    box-shadow: 0 8px 24px rgba(0,0,0,0.08);
                                                                                            object-fit: cover;
                                                                                                }
                                                                                                </style>

                                                                                                <!-- 1. HEADER BANNER TENTANG -->
                                                                                                <div class="banner-tentang text-white mb-5">
                                                                                                    <div class="container">
                                                                                                            <h1 class="text-uppercase banner-title mb-0">Tentang Kami</h1>
                                                                                                                </div>
                                                                                                                </div>

                                                                                                                <!-- 2. KONTEN TENTANG TASTY FOOD -->
                                                                                                                <div class="container my-5 py-3">
                                                                                                                    <div class="row align-items-center g-5">
                                                                                                                            <!-- Teks Kiri -->
                                                                                                                                    <div class="col-md-6">
                                                                                                                                                <h3 class="fw-bold text-uppercase mb-4" style="letter-spacing: 1px;">TASTY FOOD</h3>
                                                                                                                                                            <p class="fw-bold text-dark lh-lg mb-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ornare, augue eu rutrum commodo, dui diam convallis arcu, eget consectetur ex sem eget lacus.</p>
                                                                                                                                                                        <p class="text-muted lh-lg mb-0">Nullam vitae dignissim neque, vel luctus ex. Fusce sit amet viverra ante. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                                                                                                                                                                                </div>
                                                                                                                                                                                        <!-- Gambar Kanan -->
                                                                                                                                                                                                <div class="col-md-6">
                                                                                                                                                                                                            <div class="row g-3">
                                                                                                                                                                                                                            <div class="col-6">
                                                                                                                                                                                                                                                <img src="https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=400" class="img-fluid img-grid-tentang w-100" style="height: 220px;" alt="Tentang Kuliner">
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                <div class="col-6">
                                                                                                                                                                                                                                                                                                    <img src="https://images.unsplash.com/photo-1565958011703-44f9829ba187?q=80&w=400" class="img-fluid img-grid-tentang w-100" style="height: 220px;" alt="Tentang Makanan">
                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                            <!-- 3. VISI MISI SECTION -->
                                                                                                                                                                                                                                                                                                                                            <div class="bg-light py-5 my-5">
                                                                                                                                                                                                                                                                                                                                                <div class="container py-4">
                                                                                                                                                                                                                                                                                                                                                        <div class="row g-5">
                                                                                                                                                                                                                                                                                                                                                                    <!-- Visi -->
                                                                                                                                                                                                                                                                                                                                                                                <div class="col-md-6">
                                                                                                                                                                                                                                                                                                                                                                                                <div class="p-4 bg-white shadow-sm h-100" style="border-radius: 12px;">
                                                                                                                                                                                                                                                                                                                                                                                                                    <h4 class="fw-bold text-uppercase mb-3" style="color: #ffc107;">VISI</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <p class="text-muted lh-lg mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ornare, augue eu rutrum commodo, dui diam convallis arcu, eget consectetur ex sem eget lacus. Nullam vitae dignissim neque, vel luctus ex.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <!-- Misi -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="col-md-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="p-4 bg-white shadow-sm h-100" style="border-radius: 12px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h4 class="fw-bold text-uppercase mb-3" style="color: #ffc107;">MISI</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p class="text-muted lh-lg mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ornare, augue eu rutrum commodo, dui diam convallis arcu, eget consectetur ex sem eget lacus. Nullam vitae dignissim neque, vel luctus ex.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @endsection